# Generated by Django 6.0.6 on 2026-06-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
